controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    extender_controller:
      type: velocity_controllers/JointVelocityController

extender_controller:
  ros__parameters:
    joints: "extender_joint"

    publish_rate: 50.0

    # Velocity and acceleration limits
    has_velocity_limits: true
    has_acceleration_limits: true
    has_jerk_limits: false
    max_velocity: 1.0
    min_velocity: -1.0
    max_acceleration: 0.5
    max_jerk: 0.0
    min_jerk: 0.0

    # Topic for receiving velocity setpoints
    command_topic: "cmd_vel_extender"
    command_interface: "velocity"

    # Encoder feedback
    encoder:
      type: "incremental"
      resolution: 3200  # Number of pulses per revolution
      joint: "extender_joint"
      topic: "encoder_feedback"