controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    grabber_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - extender_joint
        - left_servo_joint
        - right_servo_joint
      command_interfaces:
        - position
