controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_broadcaster:
  ros_parameters:
    sensor_name: "imu"
    frame_id: "imu"
    publish_acceleration: true # Publish acceleration
    publish_angular_velocity: true # Publish angular velocity
    publish_orientation: true # Publish orientation

# Configure EKF filter node
ekf_filter_node:
  ros__parameters:
    frequency: 30.0 # Hz  # Frequency of the filter running
    sensor_timeout: 0.1 # seconds  # Time after which a sensor is considered to be not active
    two_d_mode: false # Enable 3D mode
    publish_tf: true
    # Frame IDs used by the EKF
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"
    odom0: "odom"   # Name of the odometry source
    odom0_config: [false, false, false, false, false, false,
                   true,  true,  true,  false, false, true,
                   false, false, false]
    imu0: "imu"
    imu0_config: [true,  true,  true,  # Enable orientation
                  true,  true,  true,  # Enable angular velocity
                  false, false, false,
                  true,  true,  true]  # Enable linear acceleration
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.10
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.015

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    #Feedback from motors is published at around 50Hz
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    #Whether to use feedback or commands for odometry calculations
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
